spring:
  profiles:
    active: @profile.env@

server:
  servlet:
    context-path: /lwn
  port: 9081

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.lwn.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mappers:
    safe-update: true
    safe-delete: true

logging:
  config: classpath:log/logback-spring.xml